CREATE DATABASE IF NOT EXISTS bug_tracker;
USE bug_tracker;

CREATE TABLE IF NOT EXISTS STAFF (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Email VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Is_Admin BOOLEAN,
    Surname VARCHAR(255) NOT NULL,
    First_Name VARCHAR(255),
    Middle_Name VARCHAR(255)
) AUTO_INCREMENT=10000;

CREATE TABLE IF NOT EXISTS USER (
    Email VARCHAR(255) NOT NULL PRIMARY KEY,
    Password VARCHAR(255) NOT NULL,
    Surname VARCHAR(255) NOT NULL,
    First_Name VARCHAR(255),
    Middle_Name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS PROJECT (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Details MEDIUMTEXT,
    Project_State ENUM('Cancelled', 'Closed', 'Open', 'Postponed') NOT NULL,
    Date_Created DATETIME NOT NULL,
    Date_Closed DATETIME
) AUTO_INCREMENT=10000;

CREATE TABLE IF NOT EXISTS COMPLAINT (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Notes MEDIUMTEXT,
    Associated_Project INT UNSIGNED NOT NULL,
    Author VARCHAR(255) NOT NULL,
    Date_Created DATETIME NOT NULL,
    Complaint_State ENUM('Acknowledged', 'Completed', 'In Progress', 'Pending') NOT NULL,
    Tags ENUM('Database', 'Functionality', 'Network', 'Performance', 'Security', 'UI'),
    FOREIGN KEY (Associated_Project) REFERENCES PROJECT(ID)
) AUTO_INCREMENT=10000;

CREATE TABLE IF NOT EXISTS TASK (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Associated_Complaint INT UNSIGNED NOT NULL,
    Task_Name VARCHAR(255) NOT NULL,
    Task_State ENUM('Completed', 'Due Today', 'In Progress', 'New', 'Overdue', 'Updated') NOT NULL,
    Due_date DATETIME NOT NULL,
    Associated_Staff INT UNSIGNED NOT NULL,
    Is_Team_Lead BOOLEAN NOT NULL,
    FOREIGN KEY (Associated_Complaint) REFERENCES COMPLAINT(ID),
    FOREIGN KEY (Associated_Staff) REFERENCES STAFF(ID)
) AUTO_INCREMENT=10000;

CREATE TABLE IF NOT EXISTS FILES (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    File_name VARCHAR(255),
    File_path TEXT NOT NULL,
    Associated_Complaint INT UNSIGNED NOT NULL,
    FOREIGN KEY (Associated_Complaint) REFERENCES COMPLAINT(ID)
);

CREATE TABLE IF NOT EXISTS STAFF_NOTE (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Note TEXT NOT NULL,
    Associated_Complaint INT UNSIGNED NOT NULL,
    FOREIGN KEY (Associated_Complaint) REFERENCES COMPLAINT(ID)
);

CREATE TABLE IF NOT EXISTS CALENDAR_EVENTS (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Associated_staff INT UNSIGNED NOT NULL,
    Date DATETIME NOT NULL,
    Event_title VARCHAR(255) NOT NULL,
    FOREIGN KEY (Associated_staff) REFERENCES STAFF(ID)
);

CREATE TABLE IF NOT EXISTS CONVERSATIONS (
    Conversation_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS CONVERSATION_PARTICIPANTS (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Conversation_ID INT UNSIGNED NOT NULL,
    Staff_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY (Conversation_ID) REFERENCES CONVERSATIONS(Conversation_ID),
    FOREIGN KEY (Staff_ID) REFERENCES STAFF(ID)
);

CREATE TABLE IF NOT EXISTS MESSAGES (
    Message_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Conversation_ID INT UNSIGNED NOT NULL,
    Staff_ID INT UNSIGNED NOT NULL,
    Message TEXT NOT NULL,
    Time_created DATETIME NOT NULL,
    FOREIGN KEY (Conversation_ID) REFERENCES CONVERSATIONS(Conversation_ID),
    FOREIGN KEY (Staff_ID) REFERENCES STAFF(ID)
);

